### PR TITLE
Fix Issue #6 (Fix reader/writer None Object Error after Release OP)

### LINKED ISSUE #6: Reader closure problem
I think there might be a problem on closing the video reader. This is the situation:
```
from vidsz.opencv import Reader

reader = Reader("static/countdown.mp4")

while reader.is_open():
    ...
    if condition:
        reader.release()
```
Since `reader.release()` does the following:
```
def release(self) -> None:
    """Release Resources
    """
    if self._video_stream is not None:
        self._video_stream.release()
        self._video_stream = None
```
on the following iteration, reader is None and thus does not have a function `isOpened()`.
Thus it raises the error: **'NoneType' object has no attribute 'isOpened'**.

I tried to check the code if there could be a better way of closing the Reader but I couldn't find one.

What about adding a condition to `reader.is_open()`, checking that `reader._video_stream is not None and ...`?

### PR DESCRIPTION
**Pull request by shivamswarnkar**
- fix #6 
- add test for the opencv-writer after release
- add test for the opencv-reader after release

### CODE REVIEW

**Comment by shivamswarnkar** [comment]
@RiccardoLincetto Hi, I tried pushing changes to your original PR but I was getting some errors, so I did this. This still has your original commits, so I hope you don't mind it.

🚀🚀  Thanks again for your contribution, we really appreciate it 🚀🚀

**Comment by RiccardoLincetto** [comment]
No problem! Is this PR going to be included in a release anytime soon?

**Comment by shivamswarnkar** [comment]
We are working on an async reading/writing feature. Once we wrap that up, we plan to release the new version. But in case that's delayed, we'll release with current new features (i.e. this fix and batching) in a week or so.

**Comment by shivamswarnkar** [comment]
@RiccardoLincetto sorry for the long delay in the release. Your changes are included in 0.2.0 release #9

**Pull request merged**
